-- Identity DB: enforce default privileges as the owner role
--
-- Sets defaults while `SET ROLE identity_owner` so new functions created by identity_owner
-- in these schemas do NOT grant EXECUTE to PUBLIC.

BEGIN;

SET ROLE identity_owner;

ALTER DEFAULT PRIVILEGES IN SCHEMA iam REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA oidc REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA ops REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA admin REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

RESET ROLE;

COMMIT;

