export const DEFAULT_PROMPT_ANALYSE_NEW_FILE = `You are an accountant and invoice analysis assistant for a Canary Islands business. Extract following information from the given document:

{fields}

DOCUMENT TYPE DETECTION:
- If this is a BANK STATEMENT or contains MULTIPLE transactions, extract EACH transaction as a separate item in the "items" array. Each item should have: name, merchant, total, currencyCode, type (income/expense), issuedAt, categoryCode, description.
- If this is a SINGLE receipt or invoice, extract it as one transaction with items being the line items on that receipt.

Where categories are:

{categories}

And projects are:

{projects}

IMPORTANT RULES:
- Do not include any other text in your response!
- If you can't find something leave it blank, NEVER make up information
- For bank statements: positive amounts are income, negative amounts are expenses
- For bank statements: use the transaction description as "name" and try to identify the merchant
- Categorize each transaction based on the merchant name and description
- Return only one object with items array containing all individual transactions`

export const DEFAULT_SETTINGS = [
  {
    code: "default_currency",
    name: "Default Currency",
    description: "Don't change this setting if you already have multi-currency transactions. I won't recalculate them.",
    value: "EUR",
  },
  {
    code: "default_category",
    name: "Default Category",
    description: "",
    value: "other",
  },
  {
    code: "default_project",
    name: "Default Project",
    description: "",
    value: "personal",
  },
  {
    code: "default_type",
    name: "Default Type",
    description: "",
    value: "expense",
  },
  {
    code: "prompt_analyse_new_file",
    name: "Prompt for Analyze Transaction",
    description: "Allowed variables: {fields}, {categories}, {categories.code}, {projects}, {projects.code}",
    value: DEFAULT_PROMPT_ANALYSE_NEW_FILE,
  },
  {
    code: "is_welcome_message_hidden",
    name: "Do not show welcome message on dashboard",
    description: "",
    value: "false",
  },
]

import { i18n } from "@/lib/i18n-db"

export const DEFAULT_CATEGORIES = [
  { code: "ads", name: i18n("Advertisement", "Publicidad"), color: "#882727", llmPrompt: "ads, promos, online ads, etc" },
  { code: "swag", name: i18n("Swag and Goods", "Merchandising"), color: "#882727", llmPrompt: "swag, stickers, goods, etc" },
  { code: "donations", name: i18n("Gifts and Donations", "Regalos y donaciones"), color: "#1e6359", llmPrompt: "donations, gifts, charity" },
  { code: "tools", name: i18n("Equipment and Tools", "Equipos y herramientas"), color: "#c69713", llmPrompt: "equipment, tools" },
  { code: "events", name: i18n("Events and Conferences", "Eventos y conferencias"), color: "#ff8b32", llmPrompt: "events, conferences" },
  { code: "food", name: i18n("Food and Drinks", "Comida y bebidas"), color: "#d40e70", llmPrompt: "food, drinks, business meals" },
  { code: "insurance", name: i18n("Insurance", "Seguros"), color: "#050942", llmPrompt: "insurance, health, life" },
  { code: "invoice", name: i18n("Invoice", "Factura"), color: "#064e85", llmPrompt: "custom invoice, bill" },
  { code: "communication", name: i18n("Mobile and Internet", "Móvil e internet"), color: "#0e7d86", llmPrompt: "mobile, internet, phone" },
  { code: "office", name: i18n("Office Supplies", "Material de oficina"), color: "#59b0b9", llmPrompt: "office, supplies, stationery" },
  { code: "online", name: i18n("Online Services", "Servicios online"), color: "#8753fb", llmPrompt: "online services, saas, subscriptions" },
  { code: "rental", name: i18n("Rental", "Alquiler"), color: "#050942", llmPrompt: "rental, lease" },
  { code: "education", name: i18n("Education", "Educación"), color: "#ee5d6c", llmPrompt: "education, professional development, trainings" },
  { code: "salary", name: i18n("Salary", "Salarios"), color: "#ce4993", llmPrompt: "salary, wages, etc" },
  { code: "fees", name: i18n("Fees", "Tasas y comisiones"), color: "#6a0d83", llmPrompt: "fees, charges, penalties, etc" },
  { code: "travel", name: i18n("Travel Expenses", "Gastos de viaje"), color: "#fb9062", llmPrompt: "travel, accommodation, etc" },
  { code: "utility_bills", name: i18n("Utility Bills", "Facturas de servicios"), color: "#af7e2e", llmPrompt: "bills, electricity, water, etc" },
  { code: "transport", name: i18n("Transport", "Transporte"), color: "#800000", llmPrompt: "transportation costs, fuel, car rental, vignettes, etc" },
  { code: "software", name: i18n("Software", "Software"), color: "#2b5a1d", llmPrompt: "software, licenses" },
  { code: "other", name: i18n("Other", "Otros"), color: "#121216", llmPrompt: "other, miscellaneous" },
]

export const DEFAULT_PROJECTS = [{ code: "personal", name: i18n("Personal", "Personal"), llmPrompt: "personal", color: "#1e202b" }]

export const DEFAULT_CURRENCIES = [
  { code: "USD", name: "$" },
  { code: "EUR", name: "€" },
  { code: "GBP", name: "£" },
  { code: "INR", name: "₹" },
  { code: "AUD", name: "$" },
  { code: "CAD", name: "$" },
  { code: "SGD", name: "$" },
  { code: "CHF", name: "Fr" },
  { code: "MYR", name: "RM" },
  { code: "JPY", name: "¥" },
  { code: "CNY", name: "¥" },
  { code: "NZD", name: "$" },
  { code: "THB", name: "฿" },
  { code: "HUF", name: "Ft" },
  { code: "AED", name: "د.إ" },
  { code: "HKD", name: "$" },
  { code: "MXN", name: "$" },
  { code: "ZAR", name: "R" },
  { code: "PHP", name: "₱" },
  { code: "SEK", name: "kr" },
  { code: "IDR", name: "Rp" },
  { code: "BRL", name: "R$" },
  { code: "SAR", name: "﷼" },
  { code: "TRY", name: "₺" },
  { code: "KES", name: "KSh" },
  { code: "KRW", name: "₩" },
  { code: "EGP", name: "£" },
  { code: "IQD", name: "ع.د" },
  { code: "NOK", name: "kr" },
  { code: "KWD", name: "د.ك" },
  { code: "RUB", name: "₽" },
  { code: "DKK", name: "kr" },
  { code: "PKR", name: "₨" },
  { code: "ILS", name: "₪" },
  { code: "PLN", name: "zł" },
  { code: "QAR", name: "﷼" },
  { code: "OMR", name: "﷼" },
  { code: "COP", name: "$" },
  { code: "CLP", name: "$" },
  { code: "TWD", name: "NT$" },
  { code: "ARS", name: "$" },
  { code: "CZK", name: "Kč" },
  { code: "VND", name: "₫" },
  { code: "MAD", name: "د.م." },
  { code: "JOD", name: "د.ا" },
  { code: "BHD", name: ".د.ب" },
  { code: "XOF", name: "CFA" },
  { code: "LKR", name: "₨" },
  { code: "UAH", name: "₴" },
  { code: "NGN", name: "₦" },
  { code: "TND", name: "د.ت" },
  { code: "UGX", name: "USh" },
  { code: "RON", name: "lei" },
  { code: "BDT", name: "৳" },
  { code: "PEN", name: "S/" },
  { code: "GEL", name: "₾" },
  { code: "XAF", name: "FCFA" },
  { code: "FJD", name: "$" },
  { code: "VEF", name: "Bs" },
  { code: "VES", name: "Bs.S" },
  { code: "BYN", name: "Br" },
  { code: "UZS", name: "лв" },
  { code: "BGN", name: "лв" },
  { code: "DZD", name: "د.ج" },
  { code: "IRR", name: "﷼" },
  { code: "DOP", name: "RD$" },
  { code: "ISK", name: "kr" },
  { code: "CRC", name: "₡" },
  { code: "SYP", name: "£" },
  { code: "JMD", name: "J$" },
  { code: "LYD", name: "ل.د" },
  { code: "GHS", name: "₵" },
  { code: "MUR", name: "₨" },
  { code: "AOA", name: "Kz" },
  { code: "UYU", name: "$U" },
  { code: "AFN", name: "؋" },
  { code: "LBP", name: "ل.ل" },
  { code: "XPF", name: "₣" },
  { code: "TTD", name: "TT$" },
  { code: "TZS", name: "TSh" },
  { code: "ALL", name: "Lek" },
  { code: "XCD", name: "$" },
  { code: "GTQ", name: "Q" },
  { code: "NPR", name: "₨" },
  { code: "BOB", name: "Bs." },
  { code: "ZWD", name: "Z$" },
  { code: "BBD", name: "$" },
  { code: "CUC", name: "$" },
  { code: "LAK", name: "₭" },
  { code: "BND", name: "$" },
  { code: "BWP", name: "P" },
  { code: "HNL", name: "L" },
  { code: "PYG", name: "₲" },
  { code: "ETB", name: "Br" },
  { code: "NAD", name: "$" },
  { code: "PGK", name: "K" },
  { code: "SDG", name: "ج.س." },
  { code: "MOP", name: "MOP$" },
  { code: "BMD", name: "$" },
  { code: "NIO", name: "C$" },
  { code: "BAM", name: "KM" },
  { code: "KZT", name: "₸" },
  { code: "PAB", name: "B/." },
  { code: "GYD", name: "$" },
  { code: "YER", name: "﷼" },
  { code: "MGA", name: "Ar" },
  { code: "KYD", name: "$" },
  { code: "MZN", name: "MT" },
  { code: "RSD", name: "дин." },
  { code: "SCR", name: "₨" },
  { code: "AMD", name: "֏" },
  { code: "AZN", name: "₼" },
  { code: "SBD", name: "$" },
  { code: "SLL", name: "Le" },
  { code: "TOP", name: "T$" },
  { code: "BZD", name: "BZ$" },
  { code: "GMD", name: "D" },
  { code: "MWK", name: "MK" },
  { code: "BIF", name: "FBu" },
  { code: "HTG", name: "G" },
  { code: "SOS", name: "S" },
  { code: "GNF", name: "FG" },
  { code: "MNT", name: "₮" },
  { code: "MVR", name: "Rf" },
  { code: "CDF", name: "FC" },
  { code: "STN", name: "Db" },
  { code: "TJS", name: "ЅМ" },
  { code: "KPW", name: "₩" },
  { code: "KGS", name: "лв" },
  { code: "LRD", name: "$" },
  { code: "LSL", name: "L" },
  { code: "MMK", name: "K" },
  { code: "GIP", name: "£" },
  { code: "MDL", name: "L" },
  { code: "CUP", name: "₱" },
  { code: "KHR", name: "៛" },
  { code: "MKD", name: "ден" },
  { code: "VUV", name: "VT" },
  { code: "ANG", name: "ƒ" },
  { code: "MRU", name: "UM" },
  { code: "SZL", name: "L" },
  { code: "CVE", name: "$" },
  { code: "SRD", name: "$" },
  { code: "SVC", name: "$" },
  { code: "BSD", name: "$" },
  { code: "RWF", name: "R₣" },
  { code: "AWG", name: "ƒ" },
  { code: "BTN", name: "Nu." },
  { code: "DJF", name: "Fdj" },
  { code: "KMF", name: "CF" },
  { code: "ERN", name: "Nfk" },
  { code: "FKP", name: "£" },
  { code: "SHP", name: "£" },
  { code: "WST", name: "WS$" },
  { code: "JEP", name: "£" },
  { code: "TMT", name: "m" },
  { code: "GGP", name: "£" },
  { code: "IMP", name: "£" },
  { code: "TVD", name: "$" },
  { code: "ZMW", name: "ZK" },
  { code: "ADA", name: "Crypto" },
  { code: "BCH", name: "Crypto" },
  { code: "BTC", name: "Crypto" },
  { code: "CLF", name: "UF" },
  { code: "CNH", name: "¥" },
  { code: "DOGE", name: "Crypto" },
  { code: "DOT", name: "Crypto" },
  { code: "ETH", name: "Crypto" },
  { code: "LINK", name: "Crypto" },
  { code: "LTC", name: "Crypto" },
  { code: "LUNA", name: "Crypto" },
  { code: "SLE", name: "Le" },
  { code: "UNI", name: "Crypto" },
  { code: "XBT", name: "Crypto" },
  { code: "XLM", name: "Crypto" },
  { code: "XRP", name: "Crypto" },
  { code: "ZWL", name: "$" },
]

export const DEFAULT_FIELDS = [
  {
    code: "name",
    name: i18n("Name", "Nombre"),
    type: "string",
    llmPrompt: "human readable name, summarize what is bought or paid for in the invoice",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: true,
    isExtra: false,
  },
  {
    code: "description",
    name: i18n("Description", "Descripción"),
    type: "string",
    llmPrompt: "description of the transaction",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "merchant",
    name: i18n("Merchant", "Comerciante"),
    type: "string",
    llmPrompt: "merchant name, use the original spelling and language",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "accountName",
    name: i18n("Account", "Cuenta"),
    type: "string",
    llmPrompt: "",
    isVisibleInList: true,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "issuedAt",
    name: i18n("Issued At", "Fecha de emisión"),
    type: "string",
    llmPrompt: "issued at date (YYYY-MM-DD format)",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: true,
    isExtra: false,
  },
  {
    code: "projectCode",
    name: i18n("Project", "Proyecto"),
    type: "string",
    llmPrompt: "project code, one of: {projects.code}",
    // Hidden from the transactions list by default — most users don't track
    // projects and the column takes up horizontal space. Still visible in
    // analysis (category×project breakdowns) and can be re-enabled per user
    // from /settings/fields.
    isVisibleInList: false,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "categoryCode",
    name: i18n("Category", "Categoría"),
    type: "string",
    llmPrompt: "category code, one of: {categories.code}",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "files",
    name: i18n("Files", "Archivos"),
    type: "string",
    llmPrompt: "",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "total",
    name: i18n("Total", "Total"),
    type: "number",
    llmPrompt: "total total of the transaction",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: true,
    isExtra: false,
  },
  {
    code: "currencyCode",
    name: i18n("Currency", "Moneda"),
    type: "string",
    llmPrompt: "currency code, ISO 4217 three letter code like USD, EUR, including crypto codes like BTC, ETH, etc",
    isVisibleInList: false,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "convertedTotal",
    name: i18n("Converted Total", "Total convertido"),
    type: "number",
    llmPrompt: "",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "convertedCurrencyCode",
    name: i18n("Converted Currency Code", "Código de moneda convertida"),
    type: "string",
    llmPrompt: "",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "type",
    name: i18n("Type", "Tipo"),
    type: "string",
    llmPrompt: "",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "note",
    name: i18n("Note", "Nota"),
    type: "string",
    llmPrompt: "",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "vat_rate",
    name: i18n("IGIC Rate", "Tipo de IGIC"),
    type: "number",
    llmPrompt: "IGIC rate in percentage 0-100",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "vat",
    name: i18n("IGIC Amount", "Importe IGIC"),
    type: "number",
    llmPrompt: "total IGIC in currency of the invoice",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: true,
  },
  {
    code: "text",
    name: i18n("Extracted Text", "Texto extraído"),
    type: "string",
    llmPrompt: "extract all recognised text from the invoice",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
]
